### ISSUE TITLE
您可能填错产品代码了，目前仅支持监控中国和日本地区的产品，注意不同国家的机型型号不同，下面是是错误信息

### ISSUE THREAD

**Issue by Zero-Yu-Jie** [MoshiCoCo/Apple-Monitor#11]
换了产品代码也不行呢。

**Comment by MoshiCoCo** [comment]
错误信息和配置信息贴一下，看上去应该就是填错产品代码了。

**Comment by MoshiCoCo** [comment]
错误信息和配置信息贴一下。 

出现这个情况一般有两种可能，你监控的位置附近没有Apple直营店或者填错产品代码了。

**Comment by hcliu987** [comment]
![image](https://github.com/MoshiCoCo/Apple-Monitor/assets/52879991/dbbc9933-2a7f-4413-907e-bdc1500ecfca)
同问题
