### ISSUE TITLE
可以支持下新的iPhone15系列机型吗

### ISSUE THREAD

**Issue by lrannn** [MoshiCoCo/Apple-Monitor#12]

**Comment by MoshiCoCo** [comment]
目前已经支持了，产品代码那里填15的代码就好了。

**Comment by MoshiCoCo** [comment]
型号 | 128G | 256G | 512G | 1TB
-- | -- | -- | -- | --
原色 | MTQ63CH/A | MTQA3CH/A | MTQF3CH/A | MTQK3CH/A
蓝色 | MTQ73CH/A | MTQC3CH/A | MTQG3CH/A | MTQL3CH/A
白色 | MTQ53CH/A | MTQ93CH/A | MTQE3CH/A | MTQJ3CH/A
黑色 | MTQ43CH/A | MTQ83CH/A | MTQD3CH/A | MTQH3CH/A



型号 | 256G | 512G | 1TB
-- | -- | -- | --
原色 | MU2Q3CH/A | MU2V3CH/A | MU603CH/A
蓝色 | MU2R3CH/A | MU2W3CH/A | MU613CH/A
白色 | MU2P3CH/A | MU2U3CH/A | MU2Y3CH/A
黑色 | MU2N3CH/A | MU2T3CH/A | MU2X3CH/A

**Comment by eason958122** [comment]
一直提示：您可能填错产品代码了

**Comment by lrannn** [comment]
好的栓Q

**Comment by lrannn** [comment]
还是提示「填错产品代码」

**Comment by MoshiCoCo** [comment]
> 一直提示：您可能填错产品代码了

地区填错了也会有这个提示哦，看看你的location参数是不是不是标准的地区格式，广西 这类自治的需要填写全称

**Comment by lrannn** [comment]
谢特，找到问题了，北京地区的Location应该是："北京 北京 朝阳区"，栓Q
