### ISSUE TITLE
可以加一个推送测试消息吗 不知道bark有没有成功

### ISSUE THREAD

**Issue by lithiumleeow** [MoshiCoCo/Apple-Monitor#14]
bark那一块填链接需要加push吗
不知道可不可以具体说一下是填哪一块儿

**Comment by MoshiCoCo** [comment]
没问题，这个优化今天上线。

**Comment by MoshiCoCo** [comment]
> bark那一块填链接需要加push吗 

文档里有提供推送地址的格式哈，是需要加/push的，推送测试消息已经优化了。
