### ISSUE TITLE
大佬请问下微信和钉钉推送如何设置呢？

### ISSUE THREAD

**Issue by whalucard** [MoshiCoCo/Apple-Monitor#15]
我看项目介绍里支持微信和钉钉推送，但配置里没有这个选项

**Comment by MoshiCoCo** [comment]
> 我看项目介绍里支持微信和钉钉推送，但配置里没有这个选项

代码里关了需要改一下代码 先用bark或者飞书吧

**Comment by whalucard** [comment]
> > 我看项目介绍里支持微信和钉钉推送，但配置里没有这个选项
> 
> 代码里关了需要改一下代码 先用bark或者飞书吧

谢谢大佬让我接触了新东西。bark也很好用
