### ISSUE TITLE
win11输入chcp 65001后依旧乱码

### ISSUE THREAD

**Issue by SagiriYuuki** [MoshiCoCo/Apple-Monitor#16]

**Comment by whalucard** [comment]
我也是win11，出chcp 65001后 显示： 闂ㄥ簵:瑗垮崟澶ф偊鍩?鍨嬪彿:iPhone聽15聽Pro 1TB 鐧借壊閽涢噾灞?鐘舵€?鏆傛棤渚涘簲

**Comment by whalucard** [comment]
不过bark的通知倒是不影响

**Comment by SagiriYuuki** [comment]
> 我也是win11，出chcp 65001后 显示： 闂ㄥ簵:瑗垮崟澶ф偊鍩?鍨嬪彿:iPhone聽15聽Pro 1TB 鐧借壊閽涢噾灞?鐘舵€?鏆傛棤渚涘簲

我这边解决了，不要用powershell窗口，用cmd运行
chcp 65001
java -jar apple-monitor-v0.0.9.jar

**Comment by whalucard** [comment]
> > 我也是win11，出chcp 65001后 显示： 闂ㄥ簵:瑗垮崟澶ф偊鍩?鍨嬪彿:iPhone聽15聽Pro 1TB 鐧借壊閽涢噾灞?鐘舵€?鏆傛棤渚涘簲
> 
> 我这边解决了，不要用powershell窗口，用cmd运行 chcp 65001 java -jar apple-monitor-v0.0.9.jar

可以了！感谢！
