### ISSUE TITLE
大佬bark可以加参数改提示音吗，默认一声半夜根本醒不了😂

### ISSUE THREAD

**Issue by Paris0-0** [MoshiCoCo/Apple-Monitor#18]
就是bark里sound=的参数

**Comment by whalucard** [comment]
哈哈 大哥好拼啊，半夜还要起来抢啊

**Comment by Paris0-0** [comment]
没办法，昨天卡了半小时没进去

**Comment by MoshiCoCo** [comment]
> 就是bark里sound=的参数

啊 先把bark推送开震动。晚上看看有没有时间，支持下这个。

**Comment by Paris0-0** [comment]
好的，谢谢大佬

**Comment by ei0ch** [comment]
> > 就是bark里sound=的参数
> 
> 啊 先把bark推送开震动。晚上看看有没有时间，支持下这个。

希望添加上url scheme，收到通知直接打开applestore，或者开放config中bark的配置

**Comment by MoshiCoCo** [comment]
> 希望添加上url scheme，收到通知直接打开applestore，或者开放config中bark的配置我们执行修改，再次感谢大佬

好的，这两天我看下。

**Comment by MoshiCoCo** [comment]
已支持。

**Comment by MoshiCoCo** [comment]
> 大佬,我填了类似alarm, telegraph  glass 但还是默认声音,是有什么地方不对吗

启动时的声音依旧是默认的，只有有货推送才会使用自定义的哦

**Comment by Paris0-0** [comment]
好的，谢谢大佬，这几天除蓝色全都没货，一声都没响过😂
