### ISSUE TITLE
[交流]有抢到的大兄弟吗

### ISSUE THREAD

**Issue by whalucard** [MoshiCoCo/Apple-Monitor#22]
我发现周六还是断断续续有货的(虽然一秒就没了),但周日一整天都没有。

**Comment by cylllllll** [comment]
![telegram-cloud-photo-size-5-6064189661414274920-y](https://github.com/MoshiCoCo/Apple-Monitor/assets/17983727/efc6f827-78d1-479b-91fc-3ab39da21974)

**Comment by whalucard** [comment]
> ![telegram-cloud-photo-size-5-6064189661414274920-y](https://user-images.githubusercontent.com/17983727/268552781-efc6f827-78d1-479b-91fc-3ab39da21974.jpg)

大兄弟是预购当天抢到的？还是后面刷到的呢？

**Comment by cylllllll** [comment]
> > ![telegram-cloud-photo-size-5-6064189661414274920-y](https://user-images.githubusercontent.com/17983727/268552781-efc6f827-78d1-479b-91fc-3ab39da21974.jpg)
> 
> 大兄弟是预购当天抢到的？还是后面刷到的呢？
![IMG_1755](https://github.com/MoshiCoCo/Apple-Monitor/assets/17983727/15925b14-94ce-4571-af09-4813c9cf96a0)

昨天刷到的

**Comment by whalucard** [comment]
> > > ![telegram-cloud-photo-size-5-6064189661414274920-y](https://user-images.githubusercontent.com/17983727/268552781-efc6f827-78d1-479b-91fc-3ab39da21974.jpg)
> > 
> > 
> > 大兄弟是预购当天抢到的？还是后面刷到的呢？
> > ![IMG_1755](https://user-images.githubusercontent.com/17983727/268561478-15925b14-94ce-4571-af09-4813c9cf96a0.JPG)
> 
> 前天刷到的

可以可以，23点58这个时间太好了，避开高峰期。我这边已经两天没动静了

**Comment by Guzebin499** [comment]
昨晚12点25分，提示有库存，6s就没了。。。

**Comment by misaya98** [comment]
每次都得重新填提货信息吗？好麻烦 时间根本不够秒没

**Comment by F5F5** [comment]
刷了3天了，暂时还没看到有
