### ISSUE TITLE
AppleMonitor error com.alibaba.fastjson2.JSONException: illegal input， offset 1, char <

### ISSUE THREAD

**Issue by paynezhuang** [MoshiCoCo/Apple-Monitor#25]
挂了一段时间出现异常，后续又正常了。看不到返回的什么。

<img width="1585" alt="image" src="https://github.com/MoshiCoCo/Apple-Monitor/assets/18189346/b72a0843-5155-48ea-8da7-c208b8b45eb1">

**Comment by MoshiCoCo** [comment]
问题不大，调低请求频率就好。
