### ISSUE TITLE
能不能推送的同时设定铃声

### ISSUE THREAD

**Issue by MingKoo** [MoshiCoCo/Apple-Monitor#32]
可以在config.json里由用户自主选择bark中的铃声。这样就不容易错过通知。谢谢

**Comment by MoshiCoCo** [comment]
已经支持自定义铃声了 只不过还没发布。周末我发一下版本

**Comment by cool6p** [comment]
Thx



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Moshi ***@***.***&gt;
发送时间: 2023年9月20日 21:37
收件人: MoshiCoCo/Apple-Monitor ***@***.***&gt;
抄送: cool6p ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [MoshiCoCo/Apple-Monitor] 能不能推送的同时设定铃声 (Issue #32)





 
已经支持自定义铃声了 只不过还没发布。周末我发一下版本

**Comment by MoshiCoCo** [comment]
已支持。

**Comment by Paris0-0** [comment]
感谢大佬支持

**Comment by MingKoo** [comment]
感谢大佬
