### ISSUE TITLE
0.1.0报错

### ISSUE THREAD

**Issue by lesswest** [MoshiCoCo/Apple-Monitor#36]
<img width="1036" alt="image" src="https://github.com/MoshiCoCo/Apple-Monitor/assets/5052375/750c1c57-e43e-472b-b89f-7f206f1c3f78">

**Comment by szfgsdnk** [comment]
+1

**Comment by lichuangnk** [comment]
我也报了这个错

**Comment by gps949** [comment]
```zip -d apple-monitor-v0.1.0.jar 'META-INF/*.RSA' 'META-INF/*.DSA' 'META-INF/*.SF'```

**Comment by MoshiCoCo** [comment]
看上去是打包的问题，晚上修复下。或者用楼上的命令临时解决下。

**Comment by MoshiCoCo** [comment]
已优化
