### ISSUE TITLE
请问飞书机器人推送怎么设置

### ISSUE THREAD

**Issue by harryh0104** [MoshiCoCo/Apple-Monitor#39]
飞书机器人推送该如何设置呢

**Comment by paynezhuang** [comment]
<img width="765" alt="image" src="https://github.com/MoshiCoCo/Apple-Monitor/assets/18189346/46a882bf-16cd-475b-b6b6-d90970a02eff">
如图配置

**Comment by harryh0104** [comment]
请问这个webhooks和secret在飞书哪里查询啊

**Comment by paynezhuang** [comment]
> 请问这个webhooks和secret在飞书哪里查询啊

飞书创建个群，在设置里面，有个群机器人，第一个就是了。
<img width="820" alt="image" src="https://github.com/MoshiCoCo/Apple-Monitor/assets/18189346/d05b0fdc-ff8e-4f9e-9874-193d4a83f389">
