### ISSUE TITLE
按照推荐cron表达式，不间断出现请求过于频繁提示

### ISSUE THREAD

**Issue by Lon1st** [MoshiCoCo/Apple-Monitor#43]
<img width="668" alt="image" src="https://github.com/MoshiCoCo/Apple-Monitor/assets/30312458/357b4f3c-771e-4cde-9310-ee9859ca3911">
只监控了2个设备，请求间隔是默认config里的12秒，依然会不间断出现提示请求过于频繁，有时终端几分钟有时十几分钟，恢复后过一会又会出现，有没有办法解决啊？

**Comment by lesswest** [comment]
一样的问题
