### ISSUE TITLE
关于 澳门店 监控的设置

### ISSUE THREAD

**Issue by macaunero** [MoshiCoCo/Apple-Monitor#6]
请问 如果要监控澳门的话这样设置有错吗？

{
  "appleTaskConfig": {
    "cronExpressions": "*/6 * * * * ?",
    "country": "CN-MACAO",
    "location": "澳門",
    "deviceCodes": [
      "MQ8A3ZA/A"
    ],
    "storeWhiteList": [
      "澳門銀河",
      "路氹金光"
    ]
  },

**Comment by MoshiCoCo** [comment]
澳门有点特殊，没有办法线上购买，所以你需要自己去官网预约

**Comment by macaunero** [comment]
监控也监控不了？

**Comment by MoshiCoCo** [comment]
> 监控也监控不了？

对，澳门这里好像是预约排队的，不是抢下单的模式。

**Comment by macaunero** [comment]
明白了。。谢谢
