### ISSUE TITLE
iPhone 16 pro的日版网页版本号不显示

### ISSUE THREAD

**Issue by tk1114632** [MoshiCoCo/Apple-Monitor#60]
例如日本苹果官网的购买网页为：
https://www.apple.com/jp/shop/buy-iphone/iphone-16-pro/6.9%E3%82%A4%E3%83%B3%E3%83%81%E3%83%87%E3%82%A3%E3%82%B9%E3%83%97%E3%83%AC%E3%82%A4-512gb-%E3%83%8A%E3%83%81%E3%83%A5%E3%83%A9%E3%83%AB%E3%83%81%E3%82%BF%E3%83%8B%E3%82%A6%E3%83%A0-sim%E3%83%95%E3%83%AA%E3%83%BC

![image](https://github.com/user-attachments/assets/91616441-c89b-4a6d-bbfc-db440fa25ca5)

不同于中国网页：https://www.apple.com.cn/shop/buy-iphone/iphone-16-pro/MYTW3CH/A

不知道作者是否了解其他的办法来获取到日版的各版本代码。

**Comment by tk1114632** [comment]
NVM. 找到了相关型号代码：

Japan

256GB Black Titanium: MYWG3J/A
512GB Black Titanium: MYWL3J/A
1TB Black Titanium: MYWQ3J/A
256GB Desert Titanium: MYWJ3J/A
512GB Desert Titanium: MYWN3J/A
1TB Desert Titanium: MYWT3J/A
256GB Natural Titanium: MYWK3J/A
512GB Natural Titanium: MYWP3J/A
1TB Natural Titanium: MYWU3J/A
256GB White Titanium: MYWH3J/A
512GB White Titanium: MYWM3J/A
1TB White Titanium: MYWR3J/A

**Comment by kiritoxkiriko** [comment]
i guess you can check out this https://theapplewiki.com/wiki/Models#iPhone
