### ISSUE TITLE
作者你好，请问为什么bark推送收不到监控的消息

### ISSUE THREAD

**Issue by LIN961122** [MoshiCoCo/Apple-Monitor#74]
按照教程设置了token后，手机只能收到一条：您的 机器人开始监控532-0003附近的Apple直营店啦。
但收不到监控信息

cofing如下
{
  "appleTaskConfig": {
    "cronExpressions": "*/15 * * * * ?",
    "country": "JP",
    "location": "532-0003",
    "deviceCodeList": [
      {
        "deviceCode": "MYWH3J/A",
        "storeWhiteList": [
          "心斎橋",
          "京都"
        ],
        "pushConfigs": [
          {
            "barkPushUrl": "https://api.day.app/push",
            "barkPushToken": "ceBz85xWbP6NFkEiopmhBi",
            "barkPushSound": "glass.caf",
            "feishuBotWebhooks": "",
            "feishuBotSecret": ""
          }
        ]
      },
      {
        "deviceCode": "MYWH3J/A",
        "storeWhiteList": [
          "心斎橋",
          "京都"
        ],
        "pushConfigs": [
          {
            "barkPushUrl": "https://api.day.app/push",
            "barkPushToken": "ceBz85xWbP6NFkEiopmhBi",
            "barkPushSound": "glass.caf",
            "feishuBotWebhooks": "",
            "feishuBotSecret": ""
          }
        ]
      }
    ]
  }
}

**Comment by MoshiCoCo** [comment]
说明没有监控到有货

**Comment by LIN961122** [comment]
> 说明没有监控到有货

非常感谢，也就是只有有货了才会才会推送提醒是么
